version: '3.7'
services:
  web:
    build: .
    container_name: wit_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
  db:
    image: mysql:8
    container_name: wit_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    # volumes:
    #   - mysql-data:/var/lib/mysql
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wit_phpmyadmin
    ports:
      - "8081:80"
    links:
      - db
    depends_on:
      - db
# volumes:
#   mysql-data: